# Generated by Django 5.2.8 on 2025-12-30 17:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_vote_votes_alter_vote_choice_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vote',
            name='unique_user_question_vote',
        ),
        migrations.RemoveIndex(
            model_name='vote',
            name='polls_vote_questio_db4555_idx',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='question',
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('user', 'choice'), name='unique_user_choice_vote'),
        ),
    ]
