# Generated by Django 5.2.8 on 2025-12-30 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_remove_vote_unique_user_question_vote_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vote',
            name='unique_user_choice_vote',
        ),
        migrations.AddField(
            model_name='vote',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polls.question'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['question', 'choice'], name='polls_vote_questio_db4555_idx'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('user', 'question'), name='unique_user_question_vote'),
        ),
    ]
