# Generated by Django 5.2.8 on 2025-12-30 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_remove_vote_unique_user_choice_vote_vote_question_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vote',
            name='unique_user_question_vote',
        ),
        migrations.RemoveIndex(
            model_name='vote',
            name='polls_vote_questio_db4555_idx',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='question',
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='polls.question'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['choice'], name='polls_vote_choice__c1d655_idx'),
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('user', 'choice'), name='unique_user_choice_vote'),
        ),
    ]
