# Generated by Django 5.2.8 on 2025-12-30 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_remove_vote_unique_user_choice_vote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='question',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polls.question'),
            preserve_default=False,
        ),
    ]
