# Generated by Django 5.2.8 on 2026-01-06 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_alter_vote_question'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vote',
            name='unique_user_question_vote',
        ),
        migrations.RemoveIndex(
            model_name='vote',
            name='polls_vote_questio_db4555_idx',
        ),
    ]
